#!/bin/bash
apt-get update && apt install -y \
	jq \
	tmux \
	tilda \
	python3 \
	python3-pip \
	python3-virtualenv \
	git \
	openvpn \
	tcpdump \
	net-tools \
	dnsutils \
	curl \
	gnome-session-common \
	gnome-settings-daemon \
	gnome-settings-daemon-common \
	gnome-shell \
	gnome-shell-common \
	gnome-shell-extension-appindicator \
	gnome-shell-extension-dash-to-panel \
	gnome-shell-extension-desktop-icons \
	gnome-shell-extension-prefs \
	xclip

cp -v kubectx kubens /usr/local/bin/

cd /tmp && \
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
unzip awscliv2.zip && \
# The default value is /usr/local/aws-cli.
sudo ./aws/install

# Download helm
curl https://get.helm.sh/helm-v3.3.3-linux-amd64.tar.gz -o helm.tar.gz && \
	tar zxvf helm.tar.gz && \
	mv linux-amd64/helm /usr/bin/local/
